### ISSUE TITLE
Long lines make code hard to review

### ISSUE THREAD

**Issue by dkegel-fastly** [stamparm/DSVW#13]
Although DSVW is indeed small, calling it 100 lines of code might be a stretch, as it uses extremely long lines to achieve this.

The long lines are hard to understand and review.

This is a security problem; attacks mentioned in https://blog.phylum.io/phylum-discovers-dozens-more-pypi-packages-attempting-to-deliver-w4sp-stealer-in-ongoing-supply-chain-attack relied on long lines to evade review.

autopep8 helps a little, but really, the code should be run through Black, which turns it into 500 lines of much more readable python.

**Comment by stamparm** [comment]
security problem :)
