### ISSUE TITLE
project lacks LICENSE file

### ISSUE THREAD

**Issue by carlosteaches** [stamparm/DSVW#3]
Hello Miroslav,

I would like to use this sample application for educational purposes, but lack of a LICENSE file makes the project Copyrighted by default, even if that's not your purpose.

I see you've licensed other projects in your profile under the MIT license.
If you're interested in other people learning from this test-bed application, can you please add a LICENSE file with a license of your choice?

Thanks a lot

CM

**Comment by stamparm** [comment]
Hi. Done. Originally, you had "Public domain" license text inside the program itself. Now added the proper LICENSE with "Unlicense" content (effectively the Public domain license)
