### ISSUE TITLE
py-lxml missing

### ISSUE THREAD

**Issue by binarymist** [stamparm/DSVW#8]
# Running

```docker
docker build . -t dsvw
```
# Results in

Sending build context to Docker daemon  143.9kB
Step 1/7 : FROM alpine:latest
 ---> 7731472c3f2a
Step 2/7 : RUN apk --no-cache add git python3 py-lxml     && rm -rf /var/cache/apk/*
 ---> Running in 14707f0cfe48
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  py-lxml (no such package):
    required by: world[py-lxml]
The command '/bin/sh -c apk --no-cache add git python3 py-lxml     && rm -rf /var/cache/apk/*' returned a non-zero code: 1

Anything newer than alpine:3.12.3 seems to be missing the package

**Comment by stamparm** [comment]
@binarymist thank you for your report. Find it "patched" now.

p.s. One note more. In latest Dockerfile, exposed port is mapped from 65412 to 65412 to reflect the info in documentation

**Comment by binarymist** [comment]
Thanks @stamparm
